//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueueManagementApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QueueManagementEntities : DbContext
    {
        public QueueManagementEntities()
            : base("name=QueueManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RedniBroevi> RedniBroevis { get; set; }
        public virtual DbSet<Uslugi> Uslugis { get; set; }
        public virtual DbSet<UsligiSalteri> UsligiSalteris { get; set; }
        public virtual DbSet<Salteri> Salteris { get; set; }
    }
}
