//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueueManagementApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsligiSalteri
    {
        public int Id { get; set; }
        public int SalterId { get; set; }
        public int UslugaId { get; set; }
    
        public virtual Salteri Salteri { get; set; }
        public virtual Uslugi Uslugi { get; set; }
    }
}
